import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation & Global UI
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.solutions': 'Solutions',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Contact',
    'nav.support': 'Get Support',
    'nav.infrastructure': 'Infrastructure',
    'nav.security': 'Security',
    'nav.software': 'Software & ERP',
    'nav.it_support': 'IT Support (AMC)',
    'nav.privacy': 'Privacy Policy',
    'nav.terms': 'Terms of Service',
    'nav.emergency': '24/7 Emergency',
    'nav.learn_more': 'Learn More',
    
    // AI Chat
    'chat.welcome': 'Hi! I am your SLISTECH Consultant. How can I help your business today?',
    'chat.placeholder': 'Ask me about networking, security...',
    'chat.badge': 'AI Consultant',
    'chat.suggestion1': 'What is an IT AMC?',
    'chat.suggestion2': 'Network security options',
    'chat.suggestion3': 'ERP for my business',
    
    // Configurator
    'config.title': 'Business Technology Roadmap',
    'config.subtitle': 'Find the perfect tech stack for your operations in 30 seconds.',
    'config.step1': 'Select Your Sector',
    'config.step2': 'Workforce Size',
    'config.step3': 'Priority Challenge',
    'config.industry.mfg': 'Corporate & Office',
    'config.industry.oil': 'Retail & Commerce',
    'config.industry.logistics': 'Logistics & Distribution',
    'config.industry.govt': 'Public Sector',
    'config.size.small': '1-50 Users',
    'config.size.med': '51-200 Users',
    'config.size.large': '200+ Users',
    'config.chal.security': 'Security/CCTV',
    'config.chal.network': 'Slow Connectivity',
    'config.chal.software': 'Paperwork/ERP',
    'config.rec.badge': 'Our Recommendation',
    'config.rec.sec.d': 'Secure your assets with ROP-compliant surveillance and biometric access control.',
    'config.rec.infra.d': 'Build a zero-downtime foundation with certified networking and fiber optics.',
    'config.rec.soft.d': 'Streamline your operations with custom ERP modules and intelligent automation.',
    'config.result.btn': 'Get My Custom Plan',
    'config.reset': 'Start Over',

    // Hero (Home)
    'hero.badge': "North Al Batinah's IT Leader",
    'hero.title': 'Technology That Speaks Your Language...',
    'hero.typewriter': 'Solutions That Match Your Ambition.',
    'hero.p': 'Trusted by OQ, PDO, and 50+ Leading Organizations to secure and empower their digital infrastructure.',
    'hero.cta_main': 'Request Free Assessment',
    'hero.cta_sec': 'View Our Work',
    'hero.partners': 'Trusted Partners',
    
    // Stats
    'stats.years': 'Years of Excellence',
    'stats.clients': 'Enterprise Clients',
    'stats.projects': 'Projects Delivered',
    'stats.response': 'Hour Response Time',
    
    // Advantage Section
    'advantage.title': 'Why Leading Businesses Choose SLISTECH',
    'advantage.1.title': 'Local Presence',
    'advantage.1.desc': 'Based right here in North Al Batinah for rapid response. We understand the local business landscape intimately.',
    'advantage.2.title': 'International Standards',
    'advantage.2.desc': 'We don\'t cut corners. Adhering to strict global best practices in security, ISO compliance, and infrastructure safety.',
    'advantage.3.title': 'Complete One-Stop-Shop',
    'advantage.3.desc': 'From fiber optic cabling to ERP software deployment, we handle your entire business ecosystem under one roof.',
    
    // Solutions Grid
    'solutions.title': 'Comprehensive Technology Ecosystem',
    'solutions.subtitle': 'We architect, build, and maintain the digital backbone of your organization.',
    'solutions.infra.title': 'Infrastructure & Networking',
    'solutions.infra.quote': 'Is slow connectivity costing you productivity?',
    'solutions.infra.tag1': 'Structured Cabling & Fiber Optics',
    'solutions.infra.tag2': 'Data Center Setup',
    'solutions.infra.tag3': 'Wireless Solutions',
    'solutions.sec.title': 'Security & Surveillance',
    'solutions.sec.quote': '"Are your assets truly protected 24/7?"',
    'solutions.sec.tag1': 'CCTV & Access Control',
    'solutions.sec.tag2': 'Cyber Security Audits',
    'solutions.sec.tag3': 'Fire Alarm Systems',
    'solutions.soft.title': 'Software & ERP',
    'solutions.soft.quote': '"Do disjointed systems slow down your operations?"',
    'solutions.soft.tag1': 'Custom Software Development',
    'solutions.soft.tag2': 'ERP Implementation (Odoo/SAP)',
    'solutions.soft.tag3': 'Cloud Migration',
    'solutions.sup.title': 'IT Support & AMC',
    'solutions.sup.quote': '"Can you afford downtime during critical hours?"',
    'solutions.sup.tag1': '24/7 Remote & On-site Support',
    'solutions.sup.tag2': 'Annual Maintenance Contracts',
    'solutions.sup.tag3': 'IT Consulting',
    
    // Infrastructure Page
    'infra.hero.badge': 'Network Architecture',
    'infra.hero.title': 'The Foundation of Reliable Operations',
    'infra.hero.p': 'Enterprise-grade networking infrastructure designed for zero downtime across North Al Batinah.',
    'infra.hero.cta': 'Request Assessment',
    'infra.challenge.title': 'The Challenge',
    'infra.challenge.p': 'Unreliable Wi-Fi, slow data transfers, or aging cabling infrastructure putting your business operations at risk.',
    'infra.challenge.cta': 'Assess Your Risks',
    'infra.services.title': 'What We Deliver',
    'infra.services.p': 'Comprehensive infrastructure solutions tailored for Oman\'s business needs.',
    'infra.services.1.t': 'Structured Cabling',
    'infra.services.1.d': 'High-performance Cat6, Cat6a, and Fiber Optics installation ensuring stable physical connectivity.',
    'infra.services.2.t': 'Enterprise Wi-Fi 6',
    'infra.services.2.d': 'High-density wireless coverage designed for high traffic areas and seamless roaming.',
    'infra.services.3.t': 'Data Center Design',
    'infra.services.3.d': 'Optimized server room layouts with focus on cooling efficiency and cable management.',
    'infra.services.4.t': 'Network Security',
    'infra.services.4.d': 'Implementation of secure segmentation, hardware firewalls, and access controls.',
    'infra.services.5.t': 'UPS Integration',
    'infra.services.5.d': 'Uninterruptible Power Supply systems to protect hardware and ensure 24/7 uptime.',
    'infra.edge.title': 'Why SLISTECH?',
    'infra.edge.1': 'Fluke-certified Testing',
    'infra.edge.2': 'ISO Standards Compliance',
    'infra.edge.3': 'Lifetime Warranty on Cabling',
    'infra.edge.4': 'Rapid On-site Support',
    'infra.cta.title': 'Ready to upgrade your infrastructure?',
    'infra.cta.p': 'Secure your operations with SLISTECH\'s certified experts in Sohar. Get a comprehensive assessment of your current setup.',
    
    // Security Page
    'sec.hero.badge': 'Trusted in North Al Batinah',
    'sec.hero.title': 'Fortifying Your Digital & Physical Assets',
    'sec.hero.p': 'Robust security solutions compliant with ROP and international standards. We secure your premises so you can focus on growth.',
    'sec.hero.cta': 'Request Security Assessment',
    'sec.threat.title': 'The Threat Landscape',
    'sec.threat.p': 'Vulnerabilities to cyber threats, inadequate access control, or outdated surveillance putting your business operations and workforce at risk.',
    'sec.services.badge': 'Our Solutions',
    'sec.services.title': 'What We Deliver',
    'sec.services.1.t': 'ROP-Compliant CCTV',
    'sec.services.1.d': 'High-definition surveillance systems meeting strict Royal Oman Police standards.',
    'sec.services.2.t': 'Biometric Access Control',
    'sec.services.2.d': 'Secure entry management and automated time attendance tracking.',
    'sec.services.3.t': 'Network Security',
    'sec.services.3.d': 'Enterprise firewall protection and persistent endpoint security.',
    'sec.services.4.t': 'Intrusion Detection',
    'sec.services.4.d': 'Proactive smart sensors for real-time prevention of unauthorized access.',
    'sec.services.5.t': 'Security Compliance',
    'sec.services.5.d': 'Vulnerability assessments and compliance consulting for local businesses.',
    'sec.edge.title': 'The SLISTECH Edge',
    'sec.edge.1.t': 'Certified Professionals',
    'sec.edge.1.d': 'Security engineers with global certifications.',
    'sec.edge.2.t': 'Local Compliance',
    'sec.edge.2.d': 'In-depth knowledge of Oman security laws.',
    'sec.edge.3.t': '24/7 Monitoring',
    'sec.edge.3.d': 'Round-the-clock protection for your peace of mind.',
    'sec.edge.4.t': 'Integrated Systems',
    'sec.edge.4.d': 'Unified control over physical and digital assets.',
    'sec.quote': '"Security is not a product, but a process. At SLISTECH, we build adaptive shields that evolve with the threats your business faces."',
    
    // Software Page
    'soft.hero.badge': 'Intelligent Systems',
    'soft.hero.title': 'Driving Efficiency Through Smart Software',
    'soft.hero.p': 'Scalable software solutions to optimize your business processes in North Al Batinah and beyond.',
    'soft.hero.cta': 'Get Started',
    'soft.divide.title': 'The Digital Divide',
    'soft.divide.p': 'Inefficient manual processes and disconnected systems are the biggest bottlenecks for business growth today. We bridge that gap.',
    'soft.suite.badge': 'Core Competencies',
    'soft.suite.title': 'Enterprise Software Suite',
    'soft.services.1.t': 'Odoo & SAP ERP',
    'soft.services.1.d': 'Custom implementation and modules tailored for your specific business workflow.',
    'soft.services.2.t': 'Web & Mobile Apps',
    'soft.services.2.d': 'Modern, responsive applications designed for field staff and executive decision-makers.',
    'soft.services.3.t': 'Cloud Infrastructure',
    'soft.services.3.d': 'High-availability migration to Azure, AWS, or local GCC cloud clusters.',
    'soft.services.4.t': 'BI & Data Dashboards',
    'soft.services.4.d': 'Real-time visualization of business metrics and operational KPIs.',
    'soft.services.5.t': 'System Integration',
    'soft.services.5.d': 'Connecting legacy equipment and modern software into a single unified dashboard.',
    'soft.services.6.t': 'Custom API Solutions',
    'soft.services.6.d': 'Secure data exchanges between your internal systems and external partners.',
    'soft.modernize.title': 'Modernize Your Operations',
    'soft.modernize.p': 'We combine local domain knowledge in North Al Batinah with international coding standards to deliver robust digital tools.',
    'soft.modernize.feat1': 'Agile Methodology',
    'soft.modernize.feat2': 'Local 24/7 Support',
    'soft.modernize.feat3': 'Scalable Architecture',
    'soft.modernize.feat4': 'User-Centric UI/UX',
    
    // IT Support Page
    'sup.hero.badge': 'Support Service',
    'sup.hero.title': 'Guaranteed Uptime. Expert Support. Always Local.',
    'sup.hero.p': 'Proactive IT managed services and Annual Maintenance Contracts designed for North Al Batinah\'s businesses.',
    'sup.hero.cta': 'Request Free Consultation',
    'sup.risk.title': 'Business Risk',
    'sup.risk.p': 'Every minute of downtime equals lost revenue. Can your business afford to wait for support from Muscat during a critical outage?',
    'sup.deliver.badge': 'What We Deliver',
    'sup.deliver.title': 'One-Stop-Shop Support',
    'sup.services.1.t': '24/7 Dedicated Support',
    'sup.services.1.d': 'Local engineers available around the clock for emergency response and remote assistance.',
    'sup.services.2.t': 'Tiered AMC Plans',
    'sup.services.2.d': 'Scalable maintenance contracts tailored to your infrastructure size and SLA requirements.',
    'sup.services.3.t': 'Hardware Procurement',
    'sup.services.3.d': 'Direct sourcing and installation of enterprise-grade hardware and software licensing.',
    'sup.services.4.t': 'Remote Management',
    'sup.services.4.d': 'Proactive system monitoring to identify and resolve issues before they affect operations.',
    'sup.services.5.t': 'IT Consultancy',
    'sup.services.5.d': 'Strategic planning for digital transformation and infrastructure roadmapping.',
    'sup.services.6.t': 'Vendor Management',
    'sup.services.6.d': 'Single point of contact for all your technology vendors, simplifying your operations.',
    'sup.custom.title': 'Need a custom Service Level Agreement?',
    'sup.custom.cta': 'Contact Our Sales Team',
    'sup.guarantee.title': 'The 2-Hour On-Site Response Guarantee',
    'sup.guarantee.p': 'For our Premium AMC partners, we guarantee an engineer will be at your facility in North Al Batinah within 120 minutes of a critical failure report.',
    'sup.guarantee.unit': 'Minute Limit',
    'sup.guarantee.note': 'Our local presence in Sohar ensures we are always minutes away, not hours.',
    'sup.loc.sohar': 'Sohar Business Hub',
    'sup.loc.shinas': 'Shinas & Liwa',
    'sup.loc.saham': 'Saham & Al Khaburah',
    
    // About Page
    'about.hero.title': 'Built in Sohar, Serving Oman\'s Businesses',
    'about.hero.p': 'Since 2017, we\'ve been the trusted technical partner for organizations that can\'t afford downtime. We understand the pulse of North Al Batinah\'s business sector.',
    'about.hero.cta': 'View Our Services',
    'about.story.badge': 'Our Story',
    'about.story.title': 'From Startup to Regional Leader',
    'about.story.p1': 'Founded in 2017 to address the slow IT support in North Al Batinah, SLISTECH has grown from a startup to a regional leader. We recognized that local businesses were often left waiting for technical support from the capital, causing costly delays.',
    'about.story.p2': 'Today, we combine international technical standards with local speed and accountability. Our presence in Sohar isn\'t just an address—it\'s a commitment to being there when our clients need us most.',
    'about.vision.title': 'Our Vision',
    'about.vision.desc': 'To be the premier IT partner in North Al Batinah, enabling businesses with technology that scales with their ambition.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'To eliminate technical complexity by providing comprehensive, one-stop-shop IT solutions that allow our clients to focus on their core business.',
    'about.sohar.badge': 'Why Sohar?',
    'about.sohar.title': 'The Sohar Strategic Advantage',
    'about.sohar.p': 'Our headquarters in Sohar isn\'t an accident—it\'s a strategic asset. By positioning ourselves in the heart of Oman\'s growth, we guarantee response times that remote providers simply cannot match.',
    'about.sohar.loc1.t': 'Rapid Response Zone',
    'about.sohar.loc1.d': 'Guaranteed under 30 minutes onsite.',
    'about.sohar.loc2.t': 'Extended Service Area',
    'about.sohar.loc2.d': 'Comprehensive coverage for North Al Batinah.',
    
    // About - Certifications
    'about.cert.title': 'Compliance & Standards',
    'about.cert.subtitle': 'We adhere to international best practices and local regulations to ensure your operations remain secure and compliant.',
    'about.cert.1.t': 'ROP Certified',
    'about.cert.1.d': 'Fully licensed by the Royal Oman Police for security and surveillance installations.',
    'about.cert.2.t': 'ISO Standards',
    'about.cert.2.d': 'Following ISO 27001 (Security) and ISO 9001 (Quality) management frameworks.',
    'about.cert.3.t': 'Vendor Certified',
    'about.cert.3.d': 'Certified partners for Cisco, Microsoft, Odoo, and Honeywell systems.',
    'about.cert.4.t': 'Safety First',
    'about.cert.4.d': 'Strict HSE protocols for on-site technical installations.',

    // Infrastructure - Standards
    'infra.stats.title': 'Certified Infrastructure Standards',
    'infra.stats.1.v': '10G',
    'infra.stats.1.l': 'Fiber Speed',
    'infra.stats.2.v': 'Fluke',
    'infra.stats.2.l': 'Certification',
    'infra.stats.3.v': 'ISO',
    'infra.stats.3.l': 'Compliance',
    'infra.stats.4.v': 'Wi-Fi 7',
    'infra.stats.4.l': 'Ready Stack',

    // Security - Badges
    'sec.badge.rop': 'ROP Compliant',
    'sec.badge.license': 'Standard License Approved',
    
    // Portfolio Page
    'port.hero.badge': 'Case Studies',
    'port.hero.title': 'Proven Excellence Across Critical Sectors',
    'port.hero.p': 'Real projects. Real results. Real impact.',
    'port.challenge': 'Challenge',
    'port.solution': 'Solution',
    'port.impact': 'Impact',
    'port.view_full': 'View Full Case Study',
    'port.load_more': 'Load More Projects',
    'port.cat.all': 'All Sectors',
    'port.cat.gov': 'Public Sector',
    'port.cat.oil': 'Energy Sector',
    'port.cat.hosp': 'Hospitality',
    'port.cat.mfg': 'Corporate & Office',
    'port.cat.ent': 'Entertainment',
    // Projects Data
    'port.p1.title': 'Supporting Rapid Operational Growth',
    'port.p1.client': 'OQ',
    'port.p1.chal': 'As OQ rapidly expanded, they required additional IT support to complement their in-house team and ensure seamless functionality across critical systems.',
    'port.p1.sol': 'SLISTECH provided supplemental IT support, offering proactive monitoring, system upgrades, and on-demand helpdesk services.',
    'port.p1.imp': 'Reduced operational bottlenecks and enhanced system reliability for uninterrupted growth.',
    'port.p2.title': 'ERP Integration for Operational Excellence',
    'port.p2.client': 'Suhar Beach Hotel',
    'port.p2.chal': 'The hotel required a customized ERP system to streamline its operations and improve guest management.',
    'port.p2.sol': 'We developed and deployed a tailored ERP solution, integrating core functions like reservations, billing, and inventory management.',
    'port.p2.imp': '15% increase in customer satisfaction and significantly improved operational efficiency.',
    'port.p3.title': 'Advanced Digital Signage Integration',
    'port.p3.client': 'VOX Cinemas',
    'port.p3.chal': 'VOX Cinemas needed a reliable digital signage solution to display real-time movie schedules and trailers across their theaters, requiring hardware that could handle continuous high-performance playback.',
    'port.p3.sol': 'We installed premium digital poster displays with integrated sequencing technology and easy-access control switches, allowing for seamless content updates and robust performance.',
    'port.p3.imp': 'Enhanced customer engagement and a modern, high-tech aesthetic that aligns with the premium VOX brand experience.',
    'port.p4.title': 'Active Directory Management & Auditing',
    'port.p4.client': 'Social Protection Fund (SPF)',
    'port.p4.chal': 'SPF required a robust solution for managing and auditing their Active Directory environment to ensure security and compliance.',
    'port.p4.sol': 'Implemented ManageEngine AD Manager & AD Audit plus Professional Edition, providing comprehensive control and visibility over user permissions and system changes.',
    'port.p4.imp': 'Strengthened security posture and simplified compliance auditing processes.',
    'port.p5.title': 'Enterprise Service Desk Implementation',
    'port.p5.client': 'ONEIC',
    'port.p5.chal': 'ONEIC needed to modernize their internal IT service management and streamline ticket handling.',
    'port.p5.sol': 'Deployed ManageEngine Service Desk Plus Standard Edition, standardizing support workflows and improving response times.',
    'port.p5.imp': 'Increased IT team productivity and improved internal user satisfaction.',
    'port.p6.title': 'SharePoint & Power App Consulting',
    'port.p6.client': 'PDO',
    'port.p6.chal': 'PDO required specialized expertise to optimize their offshore collaboration platforms and automate business processes.',
    'port.p6.sol': 'Provided expert consulting for SharePoint and Power Apps, developing custom automation and enhancing document management workflows.',
    'port.p6.imp': 'Improved offshore operational efficiency and data-driven decision making.',
    'port.p7.title': 'Financial System Integration',
    'port.p7.client': 'Bank Saderat Iran',
    'port.p7.chal': 'The bank needed to integrate their Cautionary List Management System with the Malaa Web Service for real-time compliance checks.',
    'port.p7.sol': 'Developed a secure integration layer connecting internal management systems with national financial web services.',
    'port.p7.imp': 'Automated compliance verification and reduced manual processing errors.',
    'port.p8.title': 'Network Infrastructure & Fiber Splicing',
    'port.p8.client': 'OQ / Global Computer Services',
    'port.p8.chal': 'Large-scale industrial sites required high-performance physical networking, including fiber optic connectivity and hardware mounting.',
    'port.p8.sol': 'Executed comprehensive fiber splicing, cable laying, rack installation, and camera mounting across multiple locations.',
    'port.p8.imp': 'Established a high-speed, reliable backbone for industrial communication and surveillance.',
    'port.p9.title': 'Efficient Vendor Management Systems',
    'port.p9.client': 'PDO',
    'port.p9.chal': 'PDO needed a unified system to manage multiple technology vendors and streamline procurement workflows.',
    'port.p9.sol': 'Implemented a comprehensive vendor management framework, acting as the primary point of contact for all third-party tech services.',
    'port.p9.imp': 'Simplified operations and reduced vendor-related delays by 40%.',
    'port.p10.title': 'Enterprise Mobility & Hardware Refresh',
    'port.p10.client': 'AL JAZEERA STEEL PRODUCTS CO. SAOG',
    'port.p10.chal': 'The client required a fleet of high-performance business laptops to support their mobile workforce and modern engineering applications.',
    'port.p10.sol': 'Supplied and configured Dell 7440 business laptops with Windows 11, including full enterprise security suite installation.',
    'port.p10.imp': 'Improved workforce productivity and ensured hardware compatibility with modern software standards.',
    'port.p11.title': 'Active Directory Management & Customization',
    'port.p11.client': 'Mustafa Sultan Office Technology Co. L.L.C',
    'port.p11.chal': 'The client needed specialized implementation and customization of AD management tools to handle complex user permissions and auditing.',
    'port.p11.sol': 'Deployed and customized ManageEngine AD Manager Plus, tailoring the Professional Edition to their specific organizational structure.',
    'port.p11.imp': 'Enhanced security oversight and automated routine user management tasks.',
    'port.p12.title': 'Strategic SharePoint Consultancy Outsourcing',
    'port.p12.client': 'OQ',
    'port.p12.chal': 'Requirement for dedicated SharePoint expertise to manage complex document workflows and internal portal customizations.',
    'port.p12.sol': 'Provided on-site and remote SharePoint consultants to lead digital workspace transformation projects.',
    'port.p12.imp': 'Accelerated document management automation and improved internal collaboration efficiency.',
    'port.p13.title': 'Custom Leave Management Solution',
    'port.p13.client': 'Smartface Tech Pvt. Ltd',
    'port.p13.chal': 'A manual leave tracking system was causing administrative errors and delays in payroll processing.',
    'port.p13.sol': 'Developed a custom cloud-based Leave Management application with automated approval workflows and HR integration.',
    'port.p13.imp': 'Eliminated manual tracking errors and reduced HR administrative workload by 60%.',
    'port.p14.title': 'Advanced Cybersecurity Perimeter Protection',
    'port.p14.client': 'Public Authority for SME development (Riyada)',
    'port.p14.chal': 'SMEs required robust protection against evolving cyber threats to safeguard sensitive governmental and business data.',
    'port.p14.sol': 'Implemented Sophos XG 230 Xstream Protection with 12 months of managed security services.',
    'port.p14.imp': 'Zero security breaches reported since implementation and improved network visibility.',
    'port.p15.title': 'Comprehensive Software Licensing Management',
    'port.p15.client': 'AL JAZEERA STEEL PRODUCTS CO. SAOG',
    'port.p15.chal': 'Managing diverse software licenses across the organization was becoming complex and risked non-compliance.',
    'port.p15.sol': 'Streamlined licensing for Remote Desktop Services and Microsoft Project 2021, ensuring full compliance and optimal seat utilization.',
    'port.p15.imp': 'Ensured 100% licensing compliance and reduced software procurement costs.',
    'port.p16.title': 'High-Precision Fiber Optic Splicing',
    'port.p16.client': 'GLOBAL COMPUTER SERVICES',
    'port.p16.chal': 'Critical network backbone required professional fiber splicing to ensure zero-loss data transmission.',
    'port.p16.sol': 'Executed precision fusion splicing for high-density fiber cables, including OTDR testing and certification.',
    'port.p16.imp': 'Achieved ultra-low latency network performance for critical backbone infrastructure.',
    'port.more_projects_note': 'Beyond these featured cases, SLISTECH has successfully delivered numerous other infrastructure, security, and software projects for leading organizations, ensuring operational continuity and technological advancement across the region.',
    'port.other_clients': 'Trusted by Leading Organizations',
    'port.other_clients_p': 'We provide critical IT infrastructure and support to a diverse range of sectors across Oman, ensuring reliability and security for our partners.',
    
    // Contact Page
    'contact.hero.title': 'Let\'s Build Your Technology Infrastructure',
    'contact.hero.p': 'Our team is ready to assess your needs and design a solution tailored for your business growth.',
    'contact.form.title': 'Send Us a Message',
    'contact.form.name': 'Full Name',
    'contact.form.company': 'Company Name',
    'contact.form.phone': 'Phone Number',
    'contact.form.email': 'Email Address',
    'contact.form.topic': 'What\'s Your Challenge?',
    'contact.form.survey': 'Schedule a Site Survey (Sohar Area)',
    'contact.form.message': 'Detailed Message',
    'contact.form.submit': 'Submit Request',
    'contact.form.note': 'We typically respond within 2 hours during business hours.',
    'contact.form.placeholder.name': 'John Doe',
    'contact.form.placeholder.company': 'Your Company Ltd.',
    'contact.form.placeholder.msg': 'How can we help you?',
    'contact.form.success.title': 'Message Sent Successfully!',
    'contact.form.success.msg': 'Thank you for reaching out. Our team will contact you shortly.',
    'contact.form.error.msg': 'Something went wrong. Please try again or call us directly.',
    'contact.form.submitting': 'Sending...',
    'contact.form.success.btn': 'Send another message',
    'contact.info.title': 'Contact Information',
    'contact.info.call': 'Call Us Directly:',
    'contact.info.visit': 'Visit Our Office:',
    'contact.info.email': 'Email:',
    'contact.info.availability': 'Available 24/7 for emergencies',
    'contact.emergency.title': 'Facing a Critical System Failure?',
    'contact.emergency.p': 'Don\'t wait for a form response. Call our emergency hotline now.',
    'contact.emergency.label': 'Emergency:',
    'contact.faq.title': 'Business IT FAQ',
    'contact.faq.1.q': 'How fast is your response in Sohar?',
    'contact.faq.1.a': 'For our Premium AMC partners, we guarantee an on-site engineer within 120 minutes. Most locations in the area are reached within 30-45 minutes.',
    'contact.faq.2.q': 'Are your security systems ROP-compliant?',
    'contact.faq.2.a': 'Yes, SLISTECH is fully licensed by the Royal Oman Police (ROP) for the installation and maintenance of security and surveillance systems.',
    'contact.faq.3.q': 'Do you provide 24/7 technical support?',
    'contact.faq.3.a': 'We offer 24/7 priority support for critical systems to our maintenance contract partners, ensuring your operations never stop.',
    'contact.faq.4.q': 'Can you handle large-scale fiber projects?',
    'contact.faq.4.a': 'Absolutely. We have specialized teams for structured cabling and fiber optics, complete with Fluke certification and lifetime warranty options.',

    // Software - Ecosystem
    'soft.eco.badge': 'Our Ecosystem',
    'soft.eco.title': 'Expertise in World-Class Software',
    'soft.eco.p': 'We bridge the gap between complex business challenges and industry-leading software solutions through deep technical integration and specialized knowledge.',
    'soft.eco.stat1.v': 'Expert-Led',
    'soft.eco.stat1.l': 'Implementation',
    'soft.eco.stat2.v': 'Global',
    'soft.eco.stat2.l': 'Technical Standards',
    'soft.tech.sap.d': 'Enterprise resource planning and data management solutions for global scale.',
    'soft.tech.odoo.d': 'All-in-one business software including CRM, eCommerce, and accounting.',
    'soft.tech.azure.d': 'Cloud computing services for building, testing, and managing applications.',
    'soft.tech.react.d': 'Advanced frontend development for building dynamic user interfaces.',
    'soft.tech.python.d': 'Powerful backend logic and data processing capabilities for complex systems.',
    'soft.tech.aws.d': 'Comprehensive cloud platform offering over 200 fully featured services.',
    'soft.tech.learn': 'Learn Integration',

    // IT Support - Plans
    'sup.badge.priority': '24/7 Priority Support',
    'sup.plans.title': 'Enterprise Maintenance Plans',
    'sup.plans.note': 'Standard Annual Retainer',
    'sup.plans.popular': 'Most Popular',
    'sup.plans.quote': 'Get Quote',
    'sup.plans.bronze.name': 'Bronze Plan',
    'sup.plans.bronze.price': 'Basic',
    'sup.plans.bronze.f1': 'Business Hours Only',
    'sup.plans.bronze.f2': 'Remote Support',
    'sup.plans.bronze.f3': 'Monthly Health Check',
    'sup.plans.bronze.f4': 'Next Day On-site',
    'sup.plans.silver.name': 'Silver Plan',
    'sup.plans.silver.price': 'Preferred',
    'sup.plans.silver.f1': '24/7 Remote Support',
    'sup.plans.silver.f2': '4hr On-site Guarantee',
    'sup.plans.silver.f3': 'Bi-weekly Audit',
    'sup.plans.silver.f4': 'Hardware Replacement Support',
    'sup.plans.gold.name': 'Gold Plan',
    'sup.plans.gold.price': 'Critical',
    'sup.plans.gold.f1': '24/7 On-site Guarantee',
    'sup.plans.gold.f2': '2hr Support SLA',
    'sup.plans.gold.f3': 'Weekly Vulnerability Scans',
    'sup.plans.gold.f4': 'Dedicated Engineer',
    'sup.loc.time.30': 'Under 30 Minutes',
    'sup.loc.time.45': 'Under 45 Minutes',
    'sup.loc.time.60': 'Under 60 Minutes',

    // Sohar Advantage (Home)
    'sohar.badge': 'Strategic Location',
    'sohar.title': 'Why Location Matters in IT',
    'sohar.p1': 'In critical infrastructure, every minute of downtime counts. Being based in Sohar isn\'t just an address—it\'s a commitment to rapid deployment.',
    'sohar.feature1.t': 'Rapid Response Time',
    'sohar.feature1.d': 'We guarantee on-site support within 2 hours for our Premium AMC partners.',
    'sohar.feature2.t': 'Face-to-Face Partnership',
    'sohar.feature2.d': 'Regular site visits and local accountability. We are your neighbors.',
    'sohar.cta': 'See Our Coverage Map',
    'sohar.hq': 'Sohar HQ',
    'sohar.hub': 'Strategic Operational Hub',
    'sohar.guarantee': '2hr Response Guarantee',
    
    // Clients (Home)
    'clients.title': "Powering Oman's Critical Operations",
    'clients.subtitle': "We are proud to serve the backbone of our nation's economy.",
    'clients.testimonial': '"SLISTECH transformed our legacy network into a modern, secure infrastructure. Their team\'s response time during our critical upgrade phase was impressive."',
    'clients.author.name': 'Ahmed Al-Balushi',
    'clients.author.role': 'IT Director, Leading Enterprise',
    
    // Final CTA (Home)
    'cta.title': 'Are Technical Challenges Slowing Your Growth?',
    'cta.p': "Let's audit your infrastructure and build a roadmap for security and scalability. No commitment required.",
    'cta.button': 'Schedule Free Assessment',
    
    // Footer
    'footer.desc': 'Your trusted IT infrastructure and security partner in North Al Batinah, Oman.',
    'footer.hq': 'FlatG4, Al Esa Complex, Gadfan, Sohar, Oman',
    'footer.rights': '© 2024 SLISTECH. All rights reserved.',
  },
  ar: {
    // Navigation & Global UI
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.solutions': 'حلولنا',
    'nav.portfolio': 'أعمالنا',
    'nav.contact': 'اتصل بنا',
    'nav.support': 'طلب الدعم',
    'nav.infrastructure': 'البنية التحتية',
    'nav.security': 'الأمن والحماية',
    'nav.software': 'البرمجيات و ERP',
    'nav.it_support': 'الدعم الفني (AMC)',
    'nav.privacy': 'سياسة الخصوصية',
    'nav.terms': 'شروط الخدمة',
    'nav.learn_more': 'معرفة المزيد',
    'nav.emergency': 'طوارئ 24/7',
    
    // AI Chat
    'chat.welcome': 'مرحباً! أنا مستشارك الرقمي من سليستك. كيف يمكنني مساعدة أعمالك اليوم؟',
    'chat.placeholder': 'اسألني عن الشبكات، الأمن...',
    'chat.badge': 'مستشار الذكاء الاصطناعي',
    'chat.suggestion1': 'ما هي عقود AMC؟',
    'chat.suggestion2': 'خيارات أمن الشبكات',
    'chat.suggestion3': 'نظام ERP لأعمالي',

    // Configurator
    'config.title': 'خارطة الطريق التقنية للأعمال',
    'config.subtitle': 'اكتشف الحزمة التقنية المثالية لعملياتك في 30 ثانية.',
    'config.step1': 'اختر القطاع',
    'config.step2': 'حجم القوة العاملة',
    'config.step3': 'التحدي الأهم',
    'config.industry.mfg': 'الشركات والمكاتب',
    'config.industry.oil': 'التجزئة والتجارة',
    'config.industry.logistics': 'الخدمات اللوجستية والتوزيع',
    'config.industry.govt': 'القطاع العام',
    'config.size.small': '1-50 مستخدم',
    'config.size.med': '51-200 مستخدم',
    'config.size.large': '+200 مستخدم',
    'config.chal.security': 'الأمن / الكاميرات',
    'config.chal.network': 'بطء الاتصال',
    'config.chal.software': 'الأعمال الورقية / ERP',
    'config.rec.badge': 'توصيتنا لك',
    'config.rec.sec.d': 'قم بتأمين أصولك من خلال أنظمة مراقبة متوافقة مع شرطة عمان السلطانية والتحكم في الوصول بالبصمة.',
    'config.rec.infra.d': 'ابنِ أساساً قوياً يضمن عدم توقف العمل من خلال شبكات معتمدة وألياف بصرية عالية السرعة.',
    'config.rec.soft.d': 'قم بتبسيط عملياتك من خلال وحدات ERP مخصصة وأتمتة ذكية.',
    'config.result.btn': 'احصل على خطتي المخصصة',
    'config.reset': 'ابدأ من جديد',

    // Hero (Home)
    'hero.badge': 'رائد تقنية المعلومات في شمال الباطنة',
    'hero.title': 'تكنولوجيا تتحدث لغتكم...',
    'hero.typewriter': 'حلول توازي طموحاتكم.',
    'hero.p': 'نحن محل ثقة OQ و PDO وأكثر من 50 مؤسسة رائدة لتأمين وتمكين بنيتها التحتية الرقمية.',
    'hero.cta_main': 'اطلب تقييماً مجانياً',
    'hero.cta_sec': 'شاهد أعمالنا',
    'hero.partners': 'شركاء النجاح',
    
    // Stats
    'stats.years': 'سنوات من التميز',
    'stats.clients': 'عملاء الشركات',
    'stats.projects': 'مشروع تم تسليمه',
    'stats.response': 'ساعتان زمن الاستجابة',

    // Advantage Section
    'advantage.title': 'لماذا تختار الشركات الرائدة سليستك (SLISTECH)',
    'advantage.1.title': 'تواجد محلي',
    'advantage.1.desc': 'مقرنا هنا في شمال الباطنة للاستجابة السريعة. نحن نفهم مشهد الأعمال المحلي بدقة.',
    'advantage.2.title': 'معايير دولية',
    'advantage.2.desc': 'نحن لا نتهاون في الجودة. نلتزم بأفضل الممارسات العالمية في الأمن والامتثال للأيزو وسلامة البنية التحتية.',
    'advantage.3.title': 'متجر شامل متكامل',
    'advantage.3.desc': 'من تمديدات الألياف البصرية إلى نشر برمجيات ERP، نتولى إدارة منظومتك التقنية بالكامل تحت سقف واحد.',

    // Solutions Grid
    'solutions.title': 'إدارة منظومة التكنولوجيا الشاملة',
    'solutions.subtitle': 'نحن نصمم ونبني ونحافظ على العمود الفقري الرقمي لمؤسستك.',
    'solutions.infra.title': 'البنية التحتية والشبكات',
    'solutions.infra.quote': '"هل يكلفك بطء الاتصال تراجعاً في الإنتاجية؟"',
    'solutions.infra.tag1': 'الكابلات الهيكلية والألياف البصرية',
    'solutions.infra.tag2': 'إعداد مراكز البيانات',
    'solutions.infra.tag3': 'الحلول اللاسلكية',
    'solutions.sec.title': 'الأمن والمراقبة',
    'solutions.sec.quote': '"هل أصولك محمية حقاً على مدار الساعة؟"',
    'solutions.sec.tag1': 'كاميرات المراقبة والتحكم في الوصول',
    'solutions.sec.tag2': 'تدقيق الأمن السيبراني',
    'solutions.sec.tag3': 'أنظمة إنذار الحريق',
    'solutions.soft.title': 'البرمجيات وتخطيط الموارد',
    'solutions.soft.quote': '"هل الأنظمة غير المترابطة تبطئ عملياتك؟"',
    'solutions.soft.tag1': 'تطوير البرمجيات المخصصة',
    'solutions.soft.tag2': 'تنفيذ أنظمة ERP (Odoo/SAP)',
    'solutions.soft.tag3': 'الهجرة السحابية',
    'solutions.sup.title': 'الدعم الفني وعقود الصيانة',
    'solutions.sup.quote': '"هل يمكنك تحمل فترات التوقف خلال الساعات الحرجة؟"',
    'solutions.sup.tag1': 'دعم عن بعد وميداني 24/7',
    'solutions.sup.tag2': 'عقود الصيانة السنوية',
    'solutions.sup.tag3': 'استشارات تقنية المعلومات',

    // Infrastructure Page
    'infra.hero.badge': 'بنية الشبكات',
    'infra.hero.title': 'الأساس المتين للعمليات الموثوقة',
    'infra.hero.p': 'بنية تحتية للشبكات من فئة المؤسسات مصممة لضمان عدم التوقف عن العمل في جميع أنحاء شمال الباطنة.',
    'infra.hero.cta': 'طلب تقييم',
    'infra.challenge.title': 'التحدي',
    'infra.challenge.p': 'شبكات واي فاي غير موثوقة، أو نقل بيانات بطيء، أو بنية كابلات قديمة تعرض عملياتك التجارية للخطر.',
    'infra.challenge.cta': 'قيم مخاطرك',
    'infra.services.title': 'ما نقدمه',
    'infra.services.p': 'حلول بنية تحتية شاملة مصممة خصيصاً لاحتياجات الأعمال في سلطنة عمان.',
    'infra.services.1.t': 'الكابلات الهيكلية',
    'infra.services.1.d': 'تركيب كابلات Cat6 و Cat6a والألياف البصرية عالية الأداء لضمان اتصال مادي مستقر.',
    'infra.services.2.t': 'واي فاي 6 للمؤسسات',
    'infra.services.2.d': 'تغطية لاسلكية عالية الكثافة مصممة للمناطق ذات الحركة الكثيفة والتنقل السلس.',
    'infra.services.3.t': 'تصميم مراكز البيانات',
    'infra.services.3.d': 'تصميمات غرف الخوادم المحسنة مع التركيز على كفاءة التبريد وإدارة الكابلات.',
    'infra.services.4.t': 'أمن الشبكات',
    'infra.services.4.d': 'تنفيذ تجزئة آمنة، وجدران حماية برمجية، وعناصر تحكم في الوصول.',
    'infra.services.5.t': 'تكامل أنظمة UPS',
    'infra.services.5.d': 'أنظمة إمداد الطاقة غير المنقطعة لحماية الأجهزة وضمان التشغيل على مدار الساعة.',
    'infra.edge.title': 'لماذا سليستك؟',
    'infra.edge.1': 'اختبارات معتمدة من Fluke',
    'infra.edge.2': 'الامتثال لمعايير ISO',
    'infra.edge.3': 'ضمان مدى الحياة على الكابلات',
    'infra.edge.4': 'دعم ميداني سريع',
    'infra.cta.title': 'جاهز لترقية بنيتك التحتية؟',
    'infra.cta.p': 'أمن عملياتك مع خبراء سليستك المعتمدين في صحار. احصل على تقييم شامل لإعدادك الحالي.',
    
    // Security Page
    'sec.hero.badge': 'محل ثقة في شمال الباطنة',
    'sec.hero.title': 'تحصين أصولك الرقمية والمادية',
    'sec.hero.p': 'حلول أمنية قوية متوافقة مع شرطة عمان السلطانية والمعايير الدولية. نؤمن منشآتك لتتمكن من التركيز على النمو.',
    'sec.hero.cta': 'طلب تقييم أمني',
    'sec.threat.title': 'مشهد التهديدات',
    'sec.threat.p': 'الثغرات الأمنية السيبرانية، أو عدم كفاية التحكم في الوصول، أو المراقبة القديمة تعرض عملياتك التجارية وقوتك العاملة للخطر.',
    'sec.services.badge': 'حلولنا',
    'sec.services.title': 'ما نقدمه',
    'sec.services.1.t': 'كاميرات مراقبة متوافقة مع ROP',
    'sec.services.1.d': 'أنظمة مراقبة عالية الدقة تلبي معايير شرطة عمان السلطانية الصارمة.',
    'sec.services.2.t': 'التحكم في الوصول بالبصمة',
    'sec.services.2.d': 'إدارة الدخول الآمن وتتبع الحضور والانصراف آلياً.',
    'sec.services.3.t': 'أمن الشبكات',
    'sec.services.3.d': 'حماية جدار الحماية للمؤسسات وأمن نقاط النهاية المستمر.',
    'sec.services.4.t': 'كشف التسلل',
    'sec.services.4.d': 'مستشعرات ذكية استباقية لمنع الوصول غير المصرح به في الوقت الفعلي.',
    'sec.services.5.t': 'الامتثال الأمني',
    'sec.services.5.d': 'تقييمات الضعف واستشارات الامتثال للشركات المحلية.',
    'sec.edge.title': 'ميزة سليستك',
    'sec.edge.1.t': 'محترفون معتمدون',
    'sec.edge.1.d': 'مهندسو أمن حاصلون على شهادات عالمية.',
    'sec.edge.2.t': 'الامتثال المحلي',
    'sec.edge.2.d': 'معرفة عميقة بالقوانين الأمنية العمانية.',
    'sec.edge.3.t': 'مراقبة 24/7',
    'sec.edge.3.d': 'حماية على مدار الساعة لراحة بالك.',
    'sec.edge.4.t': 'أنظمة متكاملة',
    'sec.edge.4.d': 'تحكم موحد في الأصول المادية والرقمية.',
    'sec.quote': '"الأمن ليس منتجاً، بل عملية. في سليستك، نبني دروعاً تكيفية تتطور مع التهديدات التي يواجهها عملك."',

    // Software Page
    'soft.hero.badge': 'أنظمة ذكية',
    'soft.hero.title': 'قيادة الكفاءة من خلال البرمجيات الذكية',
    'soft.hero.p': 'حلول برمجية قابلة للتطوير لتحسين عمليات عملك في شمال الباطنة وخارجها.',
    'soft.hero.cta': 'ابدأ الآن',
    'soft.divide.title': 'الفجوة الرقمية',
    'soft.divide.p': 'العمليات اليدوية غير الفعالة والأنظمة المنفصلة هي أكبر العوائق أمام نمو الأعمال اليوم. نحن نجسر تلك الفجوة.',
    'soft.suite.badge': 'الكفاءات الأساسية',
    'soft.suite.title': 'مجموعة برمجيات المؤسسات',
    'soft.services.1.t': 'أنظمة Odoo و SAP',
    'soft.services.1.d': 'تنفيذ مخصص لوحدات العمل المصممة لعمليات عملك المحددة.',
    'soft.services.2.t': 'تطبيقات الويب والجوال',
    'soft.services.2.d': 'تطبيقات حديثة وسريعة الاستجابة مصممة للموظفين الميدانيين وصناع القرار.',
    'soft.services.3.t': 'البنية التحتية السحابية',
    'soft.services.3.d': 'هجرة عالية التوفر إلى Azure أو AWS أو مجموعات السحابة المحلية في دول الخليج.',
    'soft.services.4.t': 'ذكاء الأعمال ولوحات البيانات',
    'soft.services.4.d': 'تصور في الوقت الفعلي لمقاييس الأعمال ومؤشرات الأداء التشغيلية.',
    'soft.services.5.t': 'تكامل الأنظمة',
    'soft.services.5.d': 'ربط المعدات القديمة والبرامج الحديثة في لوحة تحكم موحدة واحدة.',
    'soft.services.6.t': 'حلول API المخصصة',
    'soft.services.6.d': 'تبادل آمن للبيانات بين أنظمتك الداخلية وشركائك الخارجيين.',
    'soft.modernize.title': 'تحديث عملياتك',
    'soft.modernize.p': 'نحن نجمع بين المعرفة المحلية في شمال الباطنة ومعايير البرمجة الدولية لتقديم أدوات رقمية قوية.',
    'soft.modernize.feat1': 'منهجية Agile',
    'soft.modernize.feat2': 'دعم محلي 24/7',
    'soft.modernize.feat3': 'هندسة قابلة للتطوير',
    'soft.modernize.feat4': 'تصميم واجهة مستخدم متميزة',

    // IT Support Page
    'sup.hero.badge': 'خدمة الدعم',
    'sup.hero.title': 'ضمان التشغيل. دعم الخبراء. محلي دائماً.',
    'sup.hero.p': 'خدمات تكنولوجيا المعلومات المدارة الاستباقية وعقود الصيانة السنوية المصممة لشركات شمال الباطنة.',
    'sup.hero.cta': 'طلب استشارة مجانية',
    'sup.risk.title': 'مخاطر الأعمال',
    'sup.risk.p': 'كل دقيقة توقف تعني ضياع في الإيرادات. هل يمكن لعملك تحمل انتظار الدعم من مسقط خلال عطل حرج؟',
    'sup.deliver.badge': 'ما نقدمه',
    'sup.deliver.title': 'دعم متكامل شامل',
    'sup.services.1.t': 'دعم مخصص 24/7',
    'sup.services.1.d': 'مهندسون محليون متاحون على مدار الساعة للاستجابة للطوارئ والمساعدة عن بعد.',
    'sup.services.2.t': 'خطط AMC متدرجة',
    'sup.services.2.d': 'عقود صيانة قابلة للتطوير مصممة لتناسب حجم بنيتك التحتية ومتطلبات اتفاقية مستوى الخدمة.',
    'sup.services.3.t': 'توفير الأجهزة والمعدات',
    'sup.services.3.d': 'توفير وتركيب الأجهزة من فئة المؤسسات وتراخيص البرمجيات مباشرة.',
    'sup.services.4.t': 'الإدارة عن بعد',
    'sup.services.4.d': 'مراقبة استباقية للنظام لتحديد المشكلات وحلها قبل أن تؤثر على العمليات.',
    'sup.services.5.t': 'استشارات تقنية المعلومات',
    'sup.services.5.d': 'تخطيط استراتيجي للتحول الرقمي ورسم خارطة طريق للبنية التحتية.',
    'sup.services.6.t': 'إدارة الموردين',
    'sup.services.6.d': 'نقطة اتصال واحدة لجميع موردي التكنولوجيا لديك، مما يبسط عملياتك.',
    'sup.custom.title': 'هل تحتاج إلى اتفاقية مستوى خدمة مخصصة؟',
    'sup.custom.cta': 'اتصل بفريق المبيعات لدينا',
    'sup.guarantee.title': 'ضمان الاستجابة الميدانية خلال ساعتين',
    'sup.guarantee.p': 'لشركائنا في عقود الصيانة المميزة، نضمن وصول مهندس إلى منشأتك في شمال الباطنة في غضون 120 دقيقة من الإبلاغ عن عطل حرج.',
    'sup.guarantee.unit': 'دقيقة حد أقصى',
    'sup.guarantee.note': 'وجودنا المحلي في صحار يضمن أننا دائماً على بعد دقائق، وليس ساعات.',
    'sup.loc.sohar': 'مركز صحار للأعمال',
    'sup.loc.shinas': 'شناص ولوى',
    'sup.loc.saham': 'صحم والخابورة',
    
    // About Page
    'about.hero.title': 'تأسست في صحار، لخدمة الشركات في عمان',
    'about.hero.p': 'منذ عام 2017، نحن الشريك التقني الموثوق للمؤسسات التي لا يمكنها تحمل فترات التوقف. نحن نفهم نبض قطاع الأعمال في شمال الباطنة.',
    'about.hero.cta': 'عرض خدماتنا',
    'about.story.badge': 'قصتنا',
    'about.story.title': 'من شركة ناشئة إلى رائد إقليمي',
    'about.story.p1': 'تأسست سليستك في عام 2017 لمعالجة بطء دعم تقنية المعلومات في شمال الباطنة، وقد نمت من شركة ناشئة لتصبح رائداً إقليمياً. أدركنا أن الشركات المحلية غالباً ما تُترك بانتظار الدعم الفني من العاصمة، مما يسبب تأخيرات مكلفة.',
    'about.story.p2': 'اليوم، نجمع بين المعايير التقنية الدولية والسرعة والمسؤولية المحلية. وجودنا في صحار ليس مجرد عنوان - إنه التزام بالتواجد عندما يحتاج إلينا عملاؤنا أكثر من غيرهم.',
    'about.vision.title': 'رؤيتنا',
    'about.vision.desc': 'أن نكون الشريك التقني الأول في شمال الباطنة، لتمكين الشركات بتكنولوجيا تتوسع مع طموحاتهم.',
    'about.mission.title': 'مهمتنا',
    'about.mission.desc': 'القضاء على التعقيد التقني من خلال تقديم حلول تقنية شاملة ومتكاملة تسمح لعملائنا بالتركيز على أعمالهم الأساسية.',
    'about.sohar.badge': 'لماذا صحار؟',
    'about.sohar.title': 'الميزة الاستراتيجية لصحار',
    'about.sohar.p': 'مقرنا الرئيسي في صحار ليس صدفة - إنه أصل استراتيجي. من خلال وضع أنفسنا في قلب النمو في عمان، نضمن أوقات استجابة لا يمكن للمزودين عن بعد مطابقتها.',
    'about.sohar.loc1.t': 'منطقة الاستجابة السريعة',
    'about.sohar.loc1.d': 'ضمان الوصول الميداني في أقل من 30 دقيقة.',
    'about.sohar.loc2.t': 'منطقة الخدمة الممتدة',
    'about.sohar.loc2.d': 'تغطية شاملة لمحافظة شمال الباطنة.',
    
    // About - Certifications (Arabic)
    'about.cert.title': 'الامتثال والمعايير',
    'about.cert.subtitle': 'نحن نلتزم بأفضل الممارسات الدولية واللوائح المحلية لضمان بقاء عملياتكم آمنة ومتوافقة.',
    'about.cert.1.t': 'معتمد من شرطة عمان السلطانية',
    'about.cert.1.d': 'مرخص بالكامل من قبل شرطة عمان السلطانية لتركيبات الأمن والمراقبة.',
    'about.cert.2.t': 'معايير الأيزو',
    'about.cert.2.d': 'نتبع أطر إدارة ISO 27001 (الأمن) و ISO 9001 (الجودة).',
    'about.cert.3.t': 'شركاء معتمدون',
    'about.cert.3.d': 'شركاء معتمدون لأنظمة Cisco و Microsoft و Odoo و Honeywell.',
    'about.cert.4.t': 'السلامة أولاً',
    'about.cert.4.d': 'بروتوكولات HSE صارمة للتركيبات في الموقع.',

    // Infrastructure - Standards (Arabic)
    'infra.stats.title': 'معايير البنية التحتية المعتمدة',
    'infra.stats.1.v': '10 جيجا',
    'infra.stats.1.l': 'سرعة الألياف',
    'infra.stats.2.v': 'فلوك',
    'infra.stats.2.l': 'شهادة الاعتماد',
    'infra.stats.3.v': 'أيزو',
    'infra.stats.3.l': 'الامتثال',
    'infra.stats.4.v': 'واي فاي 7',
    'infra.stats.4.l': 'جاهز للمستقبل',

    // Security - Badges (Arabic)
    'sec.badge.rop': 'متوافق مع شرطة عمان السلطانية',
    'sec.badge.license': 'رخصة قياسية معتمدة',
    
    // Portfolio Page
    'port.hero.badge': 'دراسات الحالة',
    'port.hero.title': 'تميز مثبت عبر القطاعات الحيوية',
    'port.hero.p': 'مشاريع حقيقية. نتائج حقيقية. تأثير حقيقية.',
    'port.challenge': 'التحدي',
    'port.solution': 'الحل',
    'port.impact': 'التأثير',
    'port.view_full': 'عرض دراسة الحالة كاملة',
    'port.load_more': 'تحميل المزيد من المشاريع',
    'port.cat.all': 'جميع القطاعات',
    'port.cat.gov': 'القطاع العام',
    'port.cat.oil': 'قطاع الطاقة',
    'port.cat.hosp': 'الضيافة والسياحة',
    'port.cat.mfg': 'الشركات والمكاتب',
    'port.cat.ent': 'الترفيه والفعاليات',
    // Projects Data (Arabic)
    'port.p1.title': 'دعم النمو التشغيلي المتسارع',
    'port.p1.client': 'OQ',
    'port.p1.chal': 'مع توسع عمليات OQ بشكل سريع، احتاجوا إلى دعم فني إضافي لتكملة فريقهم الداخلي وضمان استمرارية العمل في الأنظمة الحيوية.',
    'port.p1.sol': 'قدمت سليستك دعماً فنياً تكميلياً، شمل المراقبة الاستباقية، وتحديثات الأنظمة، وخدمات الدعم الفني عند الطلب.',
    'port.p1.imp': 'تقليل اختناقات العمليات وتعزيز موثوقية النظام لضمان نمو غير منقطع.',
    'port.p2.title': 'تكامل نظام ERP للتميز التشغيلي',
    'port.p2.client': 'فندق شاطئ صحار',
    'port.p2.chal': 'احتاج الفندق إلى نظام ERP مخصص لتبسيط عملياته وتحسين إدارة الضيوف.',
    'port.p2.sol': 'قمنا بتطوير ونشر حل ERP مخصص، يدمج الوظائف الأساسية مثل الحجوزات، والفواتير، وإدارة المخزون.',
    'port.p2.imp': 'زيادة بنسبة 15% في رضا العملاء وتحسن ملحوظ في الكفاءة التشغيلية.',
    'port.p3.title': 'تكامل متقدم للوحات الإعلانية الرقمية',
    'port.p3.client': 'ڤوكس سينما',
    'port.p3.chal': 'احتاجت ڤوكس سينما إلى حل موثوق للوحات الإعلانية الرقمية لعرض جداول الأفلام والعروض الترويجية في الوقت الفعلي عبر صالاتها، مما يتطلب أجهزة قوية قادرة على العمل المستمر عالي الأداء.',
    'port.p3.sol': 'قمنا بتركيب شاشات عرض بوسترات رقمية متميزة مع تقنية تسلسل متكاملة ومفاتيح تحكم سهلة الوصول، مما يسمح بتحديثات محتوى سلسة وأداء قوي.',
    'port.p3.imp': 'تعزيز تفاعل العملاء وتقديم مظهر عصري وعالي التقنية يتماشى مع تجربة العلامة التجارية الفاخرة لـ ڤوكس.',
    'port.p4.title': 'إدارة وتدقيق الدليل النشط (Active Directory)',
    'port.p4.client': 'صندوق الحماية الاجتماعية (SPF)',
    'port.p4.chal': 'احتاج الصندوق إلى حل قوي لإدارة وتدقيق بيئة الدليل النشط لضمان الأمن والامتثال.',
    'port.p4.sol': 'تنفيذ ManageEngine AD Manager & AD Audit Plus النسخة الاحترافية، مما وفر تحكماً شاملاً ورؤية كاملة لصلاحيات المستخدمين وتغييرات النظام.',
    'port.p4.imp': 'تعزيز الموقف الأمني وتبسيط عمليات تدقيق الامتثال.',
    'port.p5.title': 'تنفيذ مكتب الخدمة للمؤسسات',
    'port.p5.client': 'ONEIC',
    'port.p5.chal': 'احتاجت شركة ONEIC إلى تحديث إدارة خدمات تقنية المعلومات الداخلية وتبسيط التعامل مع التذاكر.',
    'port.p5.sol': 'نشر ManageEngine Service Desk Plus النسخة القياسية، مما أدى إلى توحيد سير عمل الدعم وتحسين أوقات الاستجابة.',
    'port.p5.imp': 'زيادة إنتاجية فريق تقنية المعلومات وتحسين رضا المستخدمين الداخليين.',
    'port.p6.title': 'استشارات SharePoint و Power App',
    'port.p6.client': 'تنمية نفط عمان (PDO)',
    'port.p6.chal': 'احتاجت شركة PDO إلى خبرة متخصصة لتحسين منصات التعاون البحرية وأتمتة العمليات التجارية.',
    'port.p6.sol': 'تقديم استشارات خبيرة لمنصات SharePoint و Power Apps، وتطوير حلول أتمتة مخصصة وتحسين سير عمل إدارة المستندات.',
    'port.p6.imp': 'تحسين الكفاءة التشالية في العمليات البحرية واتخاذ القرارات بناءً على البيانات.',
    'port.p7.title': 'تكامل الأنظمة المالية',
    'port.p7.client': 'بنك صادرات إيران',
    'port.p7.chal': 'احتاج البنك إلى ربط نظام إدارة قائمة التحذير مع خدمة "ملاءة" (Malaa) للتحقق من الامتثال في الوقت الفعلي.',
    'port.p7.sol': 'تطوير طبقة تكامل آمنة تربط أنظمة الإدارة الداخلية مع الخدمات المالية الوطنية.',
    'port.p7.imp': 'أتمتة عملية التحقق من الامتثال وتقليل أخطاء المعالجة اليدوية.',
    'port.p8.title': 'البنية التحتية للشبكات ووصل الألياف البصرية',
    'port.p8.client': 'OQ / العالمية لخدمات الحاسب الآلي',
    'port.p8.chal': 'تطلبت المواقع الصناعية الكبرى شبكات مادية عالية الأداء، بما في ذلك توصيل الألياف البصرية وتركيب الأجهزة.',
    'port.p8.sol': 'تنفيذ عمليات وصل الألياف البصرية الشاملة، ومد الكابلات، وتركيب الرفوف، وتثبيت الكاميرات في مواقع متعددة.',
    'port.p8.imp': 'تأسيس بنية تحتية موثوقة وعالية السرعة للاتصالات الصناعية والمراقبة.',
    'port.p9.title': 'أنظمة إدارة الموردين الفعالة',
    'port.p9.client': 'تنمية نفط عمان (PDO)',
    'port.p9.chal': 'كانت PDO بحاجة إلى نظام موحد لإدارة موردي التكنولوجيا المتعددين وتبسيط سير عمل المشتريات.',
    'port.p9.sol': 'تنفيذ إطار شامل لإدارة الموردين، والعمل كنقطة اتصال رئيسية لجميع خدمات التكنولوجيا من أطراف ثالثة.',
    'port.p9.imp': 'تبسيط العمليات وتقليل التأخيرات المتعلقة بالموردين بنسبة 40%.',
    'port.p10.title': 'تحديث أجهزة الحاسب وتطوير التنقل المؤسسي',
    'port.p10.client': 'شركة الجزيرة للمنتجات الفولاذية',
    'port.p10.chal': 'احتاج العميل إلى أسطول من أجهزة الكمبيوتر المحمولة عالية الأداء لدعم القوى العاملة المتنقلة وتطبيقات الهندسة الحديثة.',
    'port.p10.sol': 'توريد وتهيئة أجهزة كمبيوتر Dell 7440 مع نظام Windows 11، بما في ذلك تثبيت مجموعة الأمان المؤسسية الكاملة.',
    'port.p10.imp': 'تحسين إنتاجية القوى العاملة وضمان توافق الأجهزة مع معايير البرمجيات الحديثة.',
    'port.p11.title': 'إدارة وتخصيص الدليل النشط (Active Directory)',
    'port.p11.client': 'مصطفى سلطان لتكنولوجيا المكاتب',
    'port.p11.chal': 'احتاج العميل إلى تنفيذ وتخصيص أدوات إدارة AD للتعامل مع أذونات المستخدمين المعقدة والتدقيق.',
    'port.p11.sol': 'نشر وتخصيص ManageEngine AD Manager Plus، مع تكييف الإصدار الاحترافي وفقاً لهيكلهم التنظيمي المحدد.',
    'port.p11.imp': 'تعزيز الرقابة الأمنية وأتمتة مهام إدارة المستخدمين الروتينية.',
    'port.p12.title': 'الاستعانة بمصادر خارجية لاستشارات SharePoint الاستراتيجية',
    'port.p12.client': 'أوكيو (OQ)',
    'port.p12.chal': 'الحاجة إلى خبرة مخصصة في SharePoint لإدارة سير عمل المستندات المعقدة وتخصيصات البوابة الداخلية.',
    'port.p12.sol': 'توفير مستشاري SharePoint في الموقع وعن بُعد لقيادة مشاريع تحول مساحة العمل الرقمية.',
    'port.p12.imp': 'تسريع أتمتة إدارة المستندات وتحسين كفاءة التعاون الداخلي.',
    'port.p13.title': 'حل مخصص لإدارة الإجازات',
    'port.p13.client': 'سمارت فيس تيك (Smartface Tech)',
    'port.p13.chal': 'كان نظام تتبع الإجازات اليدوي يتسبب في أخطاء إدارية وتأخير في معالجة الرواتب.',
    'port.p13.sol': 'تطوير تطبيق سحابي مخصص لإدارة الإجازات مع سير عمل آلي للموافقات والتكامل مع الموارد البشرية.',
    'port.p13.imp': 'القضاء على أخطاء التتبع اليدوي وتقليل عبء العمل الإداري للموارد البشرية بنسبة 60%.',
    'port.p14.title': 'حماية متقدمة للأمن السيبراني',
    'port.p14.client': 'الهيئة العامة لتنمية المؤسسات الصغيرة والمتوسطة (ريادة)',
    'port.p14.chal': 'احتاجت المؤسسات الصغيرة والمتوسطة إلى حماية قوية ضد التهديدات السيبرانية المتطورة لحماية البيانات الحكومية والتجارية الحساسة.',
    'port.p14.sol': 'تنفيذ حماية Sophos XG 230 Xstream مع 12 شهراً من خدمات الأمن المدارة.',
    'port.p14.imp': 'عدم الإبلاغ عن أي خروقات أمنية منذ التنفيذ وتحسين رؤية الشبكة.',
    'port.p15.title': 'إدارة شاملة لتراخيص البرمجيات',
    'port.p15.client': 'شركة الجزيرة للمنتجات الفولاذية',
    'port.p15.chal': 'أصبحت إدارة تراخيص البرمجيات المتنوعة عبر المؤسسة معقدة وتخاطر بعدم الامتثال.',
    'port.p15.sol': 'تبسيط التراخيص لخدمات سطح المكتب البعيد وMicrosoft Project 2021، مما يضمن الامتثال الكامل والاستخدام الأمثل.',
    'port.p15.imp': 'ضمان الامتثال للتراخيص بنسبة 100% وتقليل تكاليف شراء البرمجيات.',
    'port.p16.title': 'لحام الألياف البصرية عالي الدقة',
    'port.p16.client': 'جلوبال لخدمات الكمبيوتر',
    'port.p16.chal': 'احتاجت العمود الفقري للشبكة الحرجة إلى لحام ألياف احترافي لضمان نقل البيانات بدون فقدان.',
    'port.p16.sol': 'تنفيذ لحام صهر دقيق لكابلات الألياف عالية الكثافة، بما في ذلك اختبار OTDR والاعتماد.',
    'port.p16.imp': 'تحقيق أداء شبكة بإنتاجية عالية ووقت استجابة منخفض للغاية للبنية التحتية للشبكة الحرجة.',
    'port.more_projects_note': 'بالإضافة إلى هذه الحالات المختارة، نجحت سليستك في تنفيذ العديد من مشاريع البنية التحتية والأمن والبرمجيات الأخرى للمؤسسات الرائدة، مما يضمن استمرارية العمليات والتقدم التكنولوجي في المنطقة.',
    'port.other_clients': 'محل ثقة المؤسسات الرائدة',
    'port.other_clients_p': 'نحن نقدم بنية تحتية ودعماً تقنياً حيوياً لمجموعة متنوعة من القطاعات في عمان، مما يضمن الموثوقية والأمان لشركائنا.',
    
    // Contact Page
    'contact.hero.title': 'لنقم ببناء بنيتك التحتية التقنية',
    'contact.hero.p': 'فريقنا جاهز لتقييم احتياجاتك وتصميم حل مخصص لنمو عملك.',
    'contact.form.title': 'أرسل لنا رسالة',
    'contact.form.name': 'الاسم الكامل',
    'contact.form.company': 'اسم الشركة',
    'contact.form.phone': 'رقم الهاتف',
    'contact.form.email': 'البريد الإلكتروني',
    'contact.form.topic': 'ما هو التحدي الذي تواجهه؟',
    'contact.form.survey': 'طلب معاينة الموقع (منطقة صحار)',
    'contact.form.message': 'رسالة مفصلة',
    'contact.form.submit': 'إرسال الطلب',
    'contact.form.note': 'نرد عادةً في غضون ساعتين خلال ساعات العمل.',
    'contact.form.placeholder.name': 'أحمد علي',
    'contact.form.placeholder.company': 'شركة مسقط المحدودة',
    'contact.form.placeholder.msg': 'كيف يمكننا مساعدتك؟',
    'contact.form.success.title': 'تم إرسال الرسالة بنجاح!',
    'contact.form.success.msg': 'شكراً لتواصلك معنا. سيتصل بك فريقنا قريباً.',
    'contact.form.error.msg': 'حدث خطأ ما. يرجى المحاولة مرة أخرى أو الاتصال بنا مباشرة.',
    'contact.form.submitting': 'جاري الإرسال...',
    'contact.form.success.btn': 'أرسل رسالة أخرى',
    'contact.info.title': 'معلومات الاتصال',
    'contact.info.call': 'اتصل بنا مباشرة:',
    'contact.info.visit': 'قم بزيارة مكتبنا:',
    'contact.info.email': 'البريد الإلكتروني:',
    'contact.info.availability': 'متاحون 24/7 للحالات الطارئة',
    'contact.emergency.title': 'تواجه عطلاً حرجاً في النظام؟',
    'contact.emergency.p': 'لا تنتظر الرد على النموذج. اتصل بخط الطوارئ الساخن لدينا الآن.',
    'contact.emergency.label': 'الطوارئ:',
    'contact.faq.title': 'الأسئلة الشائعة حول تقنية المعلومات للأعمال',
    'contact.faq.1.q': 'ما مدى سرعة استجابتكم في صحار؟',
    'contact.faq.1.a': 'لشركائنا في عقود الصيانة المتميزة، نضمن حضور مهندس ميداني خلال 120 دقيقة. نصل لمعظم المواقع في المنطقة في غضون 30-45 دقيقة.',
    'contact.faq.2.q': 'هل أنظمة الأمن لديكم متوافقة مع شرطة عمان السلطانية؟',
    'contact.faq.2.a': 'نعم، سليستك مرخصة بالكامل من قبل شرطة عمان السلطانية لتركيب وصيانة أنظمة الأمن والمراقبة.',
    'contact.faq.3.q': 'هل تقدمون دعماً فنياً على مدار الساعة؟',
    'contact.faq.3.a': 'نقدم دعماً ذا أولوية على مدار الساعة للأنظمة الحرجة لشركائنا في عقود الصيانة، لضمان استمرارية عملياتكم.',
    'contact.faq.4.q': 'هل يمكنكم التعامل مع مشاريع الألياف البصرية الكبيرة؟',
    'contact.faq.4.a': 'بالتأكيد. لدينا فرق متخصصة للكابلات الهيكلية والألياف البصرية، مع شهادات Fluke وخيارات ضمان مدى الحياة.',

    // Software - Ecosystem (Arabic)
    'soft.eco.badge': 'منظومتنا التقنية',
    'soft.eco.title': 'خبرة في البرمجيات العالمية',
    'soft.eco.p': 'نحن نربط بين تحديات الأعمال المعقدة وحلول البرمجيات الرائدة عالمياً من خلال التكامل التقني العميق والمعرفة المتخصصة.',
    'soft.eco.stat1.v': 'بقيادة خبراء',
    'soft.eco.stat1.l': 'التنفيذ',
    'soft.eco.stat2.v': 'عالمي',
    'soft.eco.stat2.l': 'المعايير التقنية',
    'soft.tech.sap.d': 'حلول تخطيط موارد المؤسسات وإدارة البيانات على نطاق عالمي.',
    'soft.tech.odoo.d': 'برنامج أعمال متكامل يشمل إدارة علاقات العملاء، التجارة الإلكترونية، والمحاسبة.',
    'soft.tech.azure.d': 'خدمات الحوسبة السحابية لبناء واختبار وإدارة التطبيقات.',
    'soft.tech.react.d': 'تطوير واجهات أمامية متقدمة لبناء واجهات مستخدم ديناميكية.',
    'soft.tech.python.d': 'منطق خلفي قوي وقدرات معالجة البيانات للأنظمة المعقدة.',
    'soft.tech.aws.d': 'منصة سحابية شاملة تقدم أكثر من 200 خدمة كاملة الميزات.',
    'soft.tech.learn': 'تعلم المزيد عن التكامل',

    // IT Support - Plans (Arabic)
    'sup.badge.priority': 'دعم ذو أولوية 24/7',
    'sup.plans.title': 'خطط صيانة المؤسسات (AMC)',
    'sup.plans.note': 'رسم سنوي قياسي',
    'sup.plans.popular': 'الأكثر طلباً',
    'sup.plans.quote': 'احصل على عرض سعر',
    'sup.plans.bronze.name': 'الخطة البرونزية',
    'sup.plans.bronze.price': 'أساسي',
    'sup.plans.bronze.f1': 'ساعات العمل فقط',
    'sup.plans.bronze.f2': 'دعم عن بعد',
    'sup.plans.bronze.f3': 'فحص دوري شهري',
    'sup.plans.bronze.f4': 'دعم ميداني في اليوم التالي',
    'sup.plans.silver.name': 'الخطة الفضية',
    'sup.plans.silver.price': 'مفضل',
    'sup.plans.silver.f1': 'دعم عن بعد 24/7',
    'sup.plans.silver.f2': 'ضمان حضور ميداني خلال 4 ساعات',
    'sup.plans.silver.f3': 'تدقيق نصف شهري',
    'sup.plans.silver.f4': 'دعم استبدال الأجهزة',
    'sup.plans.gold.name': 'الخطة الذهبية',
    'sup.plans.gold.price': 'حرج',
    'sup.plans.gold.f1': 'ضمان حضور ميداني 24/7',
    'sup.plans.gold.f2': 'اتفاقية مستوى خدمة (SLA) ساعتين',
    'sup.plans.gold.f3': 'فحص ثغرات أسبوعي',
    'sup.plans.gold.f4': 'مهندس مخصص',
    'sup.loc.time.30': 'أقل من 30 دقيقة',
    'sup.loc.time.45': 'أقل من 45 دقيقة',
    'sup.loc.time.60': 'أقل من 60 دقيقة',

    // Sohar Advantage (Home) (Arabic)
    'sohar.badge': 'موقع استراتيجي',
    'sohar.title': 'لماذا يهم الموقع في تقنية المعلومات',
    'sohar.p1': 'في البنية التحتية الحيوية، كل دقيقة توقف لها ثمن. تواجدنا في صحار ليس مجرد عنوان، بل هو التزام بالانتشار السريع.',
    'sohar.feature1.t': 'زمن استجابة قياسي',
    'sohar.feature1.d': 'نضمن الدعم الميداني في غضون ساعتين لشركائنا في عقود الصيانة المميزة (AMC).',
    'sohar.feature2.t': 'شراكة مباشرة',
    'sohar.feature2.d': 'زيارات ميدانية منتظمة ومسؤولية محلية. نحن جيرانكم.',
    'sohar.cta': 'مشاهدة خريطة التغطية',
    'sohar.hq': 'مقر صحار',
    'sohar.hub': 'مركز عمليات استراتيجي',
    'sohar.guarantee': 'ضمان الاستجابة في ساعتين',

    // Clients (Home)
    'clients.title': 'تمكين العمليات الحيوية في سلطنة عُمان',
    'clients.subtitle': 'نحن فخورون بخدمة الركائز الأساسية لاقتصاد وطننا.',
    'clients.testimonial': '"قامت سليستك بتحويل شبكتنا القديمة إلى بنية تحتية حديثة وآمنة. كان زمن استجابة فريقهم خلال مرحلة التحديث الحرجة مثيراً للإعجاب."',
    'clients.author.name': 'أحمد البلوشي',
    'clients.author.role': 'مدير تقنية المعلومات، شركة رائدة',

    // Final CTA (Home)
    'cta.title': 'هل التحديات التقنية تبطئ نمو عملك؟',
    'cta.p': 'دعنا نجري تدقيقاً لبنيتك التحتية ونضع خارطة طريق للأمن والتوسع. لا يوجد التزام مطلوب.',
    'cta.button': 'جدولة تقييم مجاني',

    // Footer
    'footer.desc': 'شريكك الموثوق في البنية التحتية لتكنولوجيا المعلومات والأمن في شمال الباطنة، عمان.',
    'footer.hq': 'شقة G4، مجمع العيسى، غضفان، صحار، عُمان',
    'footer.rights': '© 2024 SLISTECH. جميع الحقوق محفوظة.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Language>(() => {
    const saved = localStorage.getItem('slistech_lang');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('slistech_lang', lang);
  }, [lang]);

  const t = (key: string) => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      <div dir={lang === 'ar' ? 'rtl' : 'ltr'} className={lang === 'ar' ? 'font-arabic' : 'font-sans'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};